-- Script pour mettre à jour la table parametres

-- Vérifier si les colonnes existent déjà avant de les ajouter
ALTER TABLE parametres
ADD COLUMN IF NOT EXISTS nom_site VARCHAR(255) DEFAULT 'AMAF-SHOP',
ADD COLUMN IF NOT EXISTS email_contact VARCHAR(255),
ADD COLUMN IF NOT EXISTS telephone VARCHAR(50),
ADD COLUMN IF NOT EXISTS adresse TEXT,
ADD COLUMN IF NOT EXISTS devise VARCHAR(10) DEFAULT 'CFA',
ADD COLUMN IF NOT EXISTS frais_livraison DECIMAL(10,2) DEFAULT 1500.00,
ADD COLUMN IF NOT EXISTS seuil_livraison_gratuite DECIMAL(10,2) DEFAULT 25000.00,
ADD COLUMN IF NOT EXISTS taxe DECIMAL(5,2) DEFAULT 18.00,
ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS favicon_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS conditions_vente TEXT,
ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS twitter_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS maintenance_mode TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS products_per_page INT DEFAULT 8,
ADD COLUMN IF NOT EXISTS promotions_per_page INT DEFAULT 6,
ADD COLUMN IF NOT EXISTS all_products_padding INT DEFAULT 20,
ADD COLUMN IF NOT EXISTS all_products_card_height INT DEFAULT 280,
ADD COLUMN IF NOT EXISTS promotions_padding INT DEFAULT 40,
ADD COLUMN IF NOT EXISTS promotions_card_height INT DEFAULT 320;
